name: ski_dev

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db
    restart: unless-stopped

  backend:
    build: ./backend
    user: root # Evita conflictos de permisos al generar llaves o migraciones en Linux/WSL
    volumes:
      - ./backend:/app # MODO DEV: Tus cambios de código se reflejan al instante
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis
    networks:
      - proxy_network
      - db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: deps
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - proxy_network
    expose:
      - "3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
volumes:
  postgres_data:

networks:
  db:
    driver: bridge
    internal: true
  proxy_network:
    external: true
