name: ski_prod

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
    restart: unless-stopped

  backend:
    # La imagen se construye en GitHub y se descarga desde GHCR
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app
      - db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - db
    restart: unless-stopped

  frontend:
    # La imagen se construye en GitHub y se descarga desde GHCR
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    env_file:
      - .env
    ports:
      - "3010:3000"
    depends_on:
      - backend
    networks:
      - app
    restart: unless-stopped

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      # Montaje hacia la carpeta NFS
      - /mnt/nas_backups/clases-vesotel:/backups
    networks:
      - db
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=3


volumes:
  postgres_data:
  redis_data:

networks:
  app:
    driver: bridge
  db:
    driver: bridge