"""Initial migration

Revision ID: 3c3e825025ae
Revises: 
Create Date: 2026-03-13 08:35:23.791998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3e825025ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_logs', 'pickup_point')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_logs', sa.Column('pickup_point', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
